# -*- coding: utf-8 -*-
"""Abstractive_Summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjMRUR_X-QfRR0h0WUrLZ57NldNN4qgA
"""


import google.generativeai as genai
import os
from dotenv import load_dotenv

load_dotenv()
key = os.getenv('GEMINI_API_KEY')
genai.configure(api_key = key)
generation_config = {'temperature' : 0.9, 'top_p' : 1, 'to_k' : 1, 'max_output_tokens': 2048}
model = genai.GenerativeModel('gemini-1.5-flash')


def abstractive_summary(text):
  response = model.generate_content([f'Write summary of the following text without bolding text: {text}'])
  return response.text